### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by githubgeeker** [thebitstick/nautilus-gnome-disks#1]
Hi, when I right click in nautilus on the "usb label" and click on "format" , sometimes the window appears and sometimes nothing happens.
In debug mode I have this errror:
**Cannot parse integer value “1e00007” for --xid**
I think that nautilus invoke this command
**gnome-disks --block-device /dev/sdx --format-device --xid xxxxxxx**
This command dont works without xid value.
What do you think about it?

**Comment by thebitstick** [comment]
You know, I'm actually an idiot. I'm so sorry.
I didn't document or even show or describe how to use this extension.
You would right-click on a IMAGE of sorts (ISO/IMG only for now), and then be taken to GNOME Disks to then select a disk.
I am so sorry I didn't make this clear.

I'm not so sure about the error you're getting, but I don't think it would have anything to do with this extension.

**Comment by githubgeeker** [comment]
Ok. Thanks for answer.
Bye!

Il lun 20 apr 2020, 19:18 TheBitStick <notifications@github.com> ha scritto:
